-- 审批任务表
CREATE TABLE IF NOT EXISTS biz_approval_task (
    id                    BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    instance_id           BIGINT(20)    NOT NULL                COMMENT '关联实例ID',
    process_definition_id BIGINT(20)                             COMMENT '流程定义ID(冗余)',
    node_id               VARCHAR(64)   NOT NULL                COMMENT '节点ID',
    node_name             VARCHAR(200)                           COMMENT '节点名称',
    node_type             VARCHAR(32)   NOT NULL                COMMENT '节点类型: approve-审批 cc-抄送 notify-通知 condition-条件分支',
    node_index            INT                                    COMMENT '节点顺序(用于展示)',
    assignee_id           BIGINT(20)                             COMMENT '审批人ID',
    assignee_name         VARCHAR(100)                           COMMENT '审批人姓名',
    assignee_type         VARCHAR(32)                            COMMENT '审批人类型: user-指定人 role-角色 supervisor-上级 dept_leader-部门负责人',
    candidate_users       TEXT                                   COMMENT '候选审批人列表JSON',
    approve_mode          VARCHAR(32)                            COMMENT '审批模式: single-单签 all-会签 any-或签',
    status                TINYINT       NOT NULL DEFAULT 0      COMMENT '状态: 0-待审批 1-已通过 2-已驳回 3-已转交 4-已超时 5-已撤销',
    opinion               VARCHAR(500)                           COMMENT '审批意见',
    attachments           TEXT                                   COMMENT '附件列表JSON',
    signature             VARCHAR(500)                           COMMENT '电子签名',
    receive_time          DATETIME                               COMMENT '收到任务时间',
    deadline              DATETIME                               COMMENT '截止时间',
    remind_time           DATETIME                               COMMENT '最后一次提醒时间',
    complete_time         DATETIME                               COMMENT '完成时间',
    remark                VARCHAR(500)                           COMMENT '备注',
    create_time           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP                 COMMENT '创建时间',
    update_time           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by             VARCHAR(100)                           COMMENT '创建人',
    update_by             VARCHAR(100)                           COMMENT '更新人',
    deleted               TINYINT       NOT NULL DEFAULT 0      COMMENT '是否删除1-是、0-否',
    PRIMARY KEY (id),
    KEY idx_instance_id (instance_id),
    KEY idx_assignee_id (assignee_id),
    KEY idx_status (status),
    KEY idx_node_id (node_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审批任务表';
