-- 清空所有 Activiti 表，让引擎重新创建
-- 适用于 schema.version 冲突（如 6.8.0.0 vs 7.1.0.M6）的情况

SET FOREIGN_KEY_CHECKS = 0;

-- ACT_RE_* (Repository)
DROP TABLE IF EXISTS ACT_RE_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_RE_PROCDEF;
DROP TABLE IF EXISTS ACT_RE_MODEL;

-- ACT_RU_* (Runtime)
DROP TABLE IF EXISTS ACT_RU_EXECUTION;
DROP TABLE IF EXISTS ACT_RU_JOB;
DROP TABLE IF EXISTS ACT_RU_TIMER_JOB;
DROP TABLE IF EXISTS ACT_RU_SECO_JOB;
DROP TABLE IF EXISTS ACT_RU_TASK;
DROP TABLE IF EXISTS ACT_RU_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_RU_VARIABLE;
DROP TABLE IF EXISTS ACT_RU_EVENT_SUBSCR;

-- ACT_HI_* (History)
DROP TABLE IF EXISTS ACT_HI_PROCINST;
DROP TABLE IF EXISTS ACT_HI_ACTINST;
DROP TABLE IF EXISTS ACT_HI_TASKINST;
DROP TABLE IF EXISTS ACT_HI_VARINST;
DROP TABLE IF EXISTS ACT_HI_DETAIL;
DROP TABLE IF EXISTS ACT_HI_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_HI_COMMENT;
DROP TABLE IF EXISTS ACT_HI_ATTACHMENT;
DROP TABLE IF EXISTS ACT_HI_OPLOG;

-- ACT_GE_* (General)
DROP TABLE IF EXISTS ACT_GE_PROPERTY;
DROP TABLE IF EXISTS ACT_GE_BYTEARRAY;

-- ACT_ID_* (Identity) - Activiti 7 可能不使用，但以防万一
DROP TABLE IF EXISTS ACT_ID_USER;
DROP TABLE IF EXISTS ACT_ID_INFO;
DROP TABLE IF EXISTS ACT_ID_GROUP;
DROP TABLE IF EXISTS ACT_ID_MEMBERSHIP;
DROP TABLE IF EXISTS ACT_ID_TENANT;
DROP TABLE IF EXISTS ACT_ID_TENANT_MEMBER;

-- ACT_EVT_LOG
DROP TABLE IF EXISTS ACT_EVT_LOG;

SET FOREIGN_KEY_CHECKS = 1;
