CREATE TABLE IF NOT EXISTS biz_leave (
    id              BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT '主键',
    title           VARCHAR(255)  NOT NULL                COMMENT '请假标题',
    leave_type      TINYINT       NOT NULL                COMMENT '请假类型 1年假 2事假 3病假 4婚假 5产假 6丧假 7其他',
    start_date      DATE          NOT NULL                COMMENT '开始日期',
    end_date        DATE          NOT NULL                COMMENT '结束日期',
    days            DECIMAL(5,1)  NOT NULL                COMMENT '请假天数(支持0.5天)',
    reason          VARCHAR(500)  NOT NULL                COMMENT '请假原因',
    applicant_id    BIGINT(20)    NOT NULL                COMMENT '申请人ID',
    applicant_name  VARCHAR(100)                          COMMENT '申请人姓名(冗余)',
    dept_name       VARCHAR(100)                          COMMENT '申请人部门(冗余)',
    status          TINYINT       NOT NULL DEFAULT 0      COMMENT '状态 0待审批 1审批中 2已通过 3已驳回 4已撤回',
    process_instance_id BIGINT(20)                        COMMENT '关联流程实例ID(sys_process_instance.id)',
    approve_comment VARCHAR(500)                          COMMENT '审批意见',
    create_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by       VARCHAR(100)                          COMMENT '创建人',
    update_by       VARCHAR(100)                          COMMENT '更新人',
    deleted         TINYINT       NOT NULL DEFAULT 0      COMMENT '是否删除1-是、0-否',
    PRIMARY KEY (id),
    KEY idx_applicant_id (applicant_id),
    KEY idx_status (status),
    KEY idx_leave_type (leave_type),
    KEY idx_start_date (start_date),
    KEY idx_process_instance_id (process_instance_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='请假单表';
