-- 流程实例业务表
-- 与 Activiti 引擎表互补，存储业务侧数据
CREATE TABLE IF NOT EXISTS sys_process_instance (
    id                              BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT '主键',
    title                           VARCHAR(255)  NOT NULL                COMMENT '审批标题',
    instance_no                     VARCHAR(64)                           COMMENT '实例编号(如PROC202606130001)',
    act_process_instance_id          VARCHAR(64)   NOT NULL                COMMENT 'Activiti流程实例ID',
    process_definition_id           BIGINT(20)    NOT NULL                COMMENT '关联流程定义ID(sys_process_definition.id)',
    process_definition_key          VARCHAR(255)  NOT NULL                COMMENT '流程定义标识(冗余，便于查询)',
    process_name                    VARCHAR(255)                          COMMENT '流程名称(冗余)',
    business_key                    VARCHAR(255)                          COMMENT '业务单据号(关联业务表)',
    business_type                   VARCHAR(64)                           COMMENT '业务类型(如: leave/expense/purchase)',
    business_id                     BIGINT(20)                            COMMENT '业务单据主键ID(如请假单ID)',
    start_user_id                   BIGINT(20)    NOT NULL                COMMENT '发起人ID(sys_user.id)',
    start_user_name                 VARCHAR(100)                          COMMENT '发起人姓名(冗余)',
    applicant_dept_id               BIGINT(20)                            COMMENT '发起人部门ID',
    status                          TINYINT       NOT NULL DEFAULT 0      COMMENT '状态 0运行中 1已完成 2已终止 3已撤回',
    current_node_name               VARCHAR(255)                          COMMENT '当前节点名称(冗余，便于列表展示)',
    current_node_id                 VARCHAR(255)                          COMMENT '当前节点ID',
    current_assignees               TEXT                                  COMMENT '当前待审批人列表JSON(如:[{"userId":1,"userName":"张三"}])',
    total_nodes                     INT                                   COMMENT '总审批节点数',
    completed_nodes                 INT           NOT NULL DEFAULT 0      COMMENT '已完成节点数',
    priority                        TINYINT       NOT NULL DEFAULT 0      COMMENT '优先级 0普通 1紧急 2特急',
    delete_reason                   VARCHAR(500)                          COMMENT '终止/撤回原因',
    variables_json                  TEXT                                  COMMENT '流程变量JSON(快照)',
    start_time                      DATETIME      NOT NULL                COMMENT '启动时间',
    end_time                        DATETIME                              COMMENT '结束时间',
    create_time                     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP                 COMMENT '创建时间',
    update_time                     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by                       VARCHAR(100)                          COMMENT '创建人',
    update_by                       VARCHAR(100)                          COMMENT '更新人',
    deleted                         TINYINT       NOT NULL DEFAULT 0      COMMENT '是否删除1-是、0-否',
    PRIMARY KEY (id),
    UNIQUE KEY uk_act_pid (act_process_instance_id),
    UNIQUE KEY uk_instance_no (instance_no),
    KEY idx_process_definition_id (process_definition_id),
    KEY idx_business_key (business_type, business_key),
    KEY idx_start_user_id (start_user_id),
    KEY idx_status (status),
    KEY idx_start_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程实例表';
