// bpmn-js 中文翻译字典（完整版）
const translations: Record<string, string> = {
  // 调色板工具
  'Create StartEvent': '创建开始事件',
  'Create EndEvent': '创建结束事件',
  'Create UserTask': '创建用户任务',
  'Create ServiceTask': '创建服务任务',
  'Create ScriptTask': '创建脚本任务',
  'Create Exclusive Gateway': '创建排他网关',
  'Create Parallel Gateway': '创建并行网关',
  'Create Inclusive Gateway': '创建包容网关',
  'Create Intermediate/Boundary Event': '创建中间/边界事件',
  'Create Expandable SubProcess': '创建可展开子流程',
  'Create Pool/Participant': '创建池/参与者',
  'Create DataObjectReference': '创建数据对象',
  'Create DataStoreReference': '创建数据存储',
  'Create Group': '创建分组',
  'Create CallActivity': '创建调用活动',
  'Create ReceiveTask': '创建接收任务',
  'Create SendTask': '创建发送任务',
  'Create ManualTask': '创建手动任务',
  'Create BusinessRuleTask': '创建业务规则任务',
  'Create SubProcess': '创建子流程',
  'Create EventSubProcess': '创建事件子流程',
  'Create Transaction': '创建事务',
  'Create ConditionalIntermediateCatchEvent': '创建条件中间捕获事件',
  'Create TimerIntermediateCatchEvent': '创建定时中间捕获事件',
  'Create SignalIntermediateCatchEvent': '创建信号中间捕获事件',
  'Create MessageIntermediateCatchEvent': '创建消息中间捕获事件',
  'Create LinkIntermediateCatchEvent': '创建链接中间捕获事件',
  'Create LinkIntermediateThrowEvent': '创建链接中间抛出事件',
  'Create SignalIntermediateThrowEvent': '创建信号中间抛出事件',
  'Create MessageIntermediateThrowEvent': '创建消息中间抛出事件',
  'Create EscalationIntermediateThrowEvent': '创建升级中间抛出事件',
  'Create CompensationIntermediateThrowEvent': '创建补偿中间抛出事件',
  'Create ErrorEndEvent': '创建错误结束事件',
  'Create EscalationEndEvent': '创建升级结束事件',
  'Create CancelEndEvent': '创建取消结束事件',
  'Create CompensationEndEvent': '创建补偿结束事件',
  'Create SignalEndEvent': '创建信号结束事件',
  'Create TerminateEndEvent': '创建终止结束事件',
  'Create TimerBoundaryEvent': '创建定时边界事件',
  'Create SignalBoundaryEvent': '创建信号边界事件',
  'Create MessageBoundaryEvent': '创建消息边界事件',
  'Create ConditionalBoundaryEvent': '创建条件边界事件',
  'Create EscalationBoundaryEvent': '创建升级边界事件',
  'Create ErrorBoundaryEvent': '创建错误边界事件',
  'Create CancelBoundaryEvent': '创建取消边界事件',
  'Create CompensationBoundaryEvent': '创建补偿边界事件',
  'Create Non-Interrupting Timer Boundary Event': '创建非中断定时边界事件',
  'Create Non-Interrupting Signal Boundary Event': '创建非中断信号边界事件',
  'Create Non-Interrupting Message Boundary Event': '创建非中断消息边界事件',
  'Create Non-Interrupting Conditional Boundary Event': '创建非中断条件边界事件',
  'Create Non-Interrupting Escalation Boundary Event': '创建非中断升级边界事件',

  // 右键上下文菜单
  'Append EndEvent': '追加结束事件',
  'Append Gateway': '追加网关',
  'Append Task': '追加任务',
  'Append UserTask': '追加用户任务',
  'Append Intermediate/Boundary Event': '追加中间/边界事件',
  'Append CallActivity': '追加调用活动',
  'Change type': '更改类型',
  'Remove': '删除',
  'Connect using Sequence/MessageFlow': '使用顺序/消息流连接',
  'Connect using DataAssociation': '使用数据关联连接',
  'Toggle collapse': '折叠/展开',
  'Delete lane': '删除泳道',
  'Add lane above': '在上方添加泳道',
  'Add lane below': '在下方添加泳道',
  'Split lane': '分割泳道',
  'Lane above': '上方泳道',
  'Lane below': '下方泳道',

  // 工具栏提示
  'Activate the hand tool': '激活抓手工具',
  'Activate the lasso tool': '激活套索工具',
  'Activate the create/remove space tool': '激活创建/移除空间工具',
  'Activate the global connect tool': '激活全局连接工具',
  'Ad-hoc marker': '自适应标记',
  'Compensation marker': '补偿标记',
  'Multi-instance marker': '多实例标记',
  'Loop marker': '循环标记',
  'Sequential marker': '顺序标记',
  'Parallel marker': '并行标记',
  'Hide status indicator': '隐藏状态指示器',

  // 属性面板 - 分组标签
  'General': '常规',
  'Details': '详情',
  'Documentation': '文档',
  'Extensions': '扩展',
  'Properties': '属性',
  'BPMN': 'BPMN',
  'CMMN': 'CMMN',
  'Errors': '错误',
  'Constraints': '约束',
  'Forms': '表单',
  'Form': '表单',
  'Headers': '请求头',
  'Scope': '范围',
  'Config': '配置',
  'Link': '链接',
  'Inputs': '输入',
  'Outputs': '输出',
  'In mappings': '输入映射',
  'Out mappings': '输出映射',
  'In mapping propagation': '输入映射传播',
  'Out mapping propagation': '输出映射传播',
  'Input propagation': '输入传播',
  'Output propagation': '输出传播',
  'Input mapping': '输入映射',
  'Output mapping': '输出映射',
  'Asynchronous continuations': '异步延续',
  'Job execution': '作业执行',
  'History cleanup': '历史清理',
  'Extension properties': '扩展属性',
  'Field injections': '字段注入',
  'Field injection': '字段注入',
  'Execution listeners': '执行监听器',
  'Execution listeners documentation': '执行监听器文档',
  'Task listeners': '任务监听器',
  'Task listeners documentation': '任务监听器文档',
  'User assignment': '用户分配',
  'Multi-instance': '多实例',
  'Multi instance documentation': '多实例文档',
  'Assignment': '分配',
  'Assignment type': '分配类型',
  'Assigning': '分配中',
  'Completing': '完成中',
  'Updating': '更新中',
  'Canceling': '取消中',
  'Connector': '连接器',
  'Connector ID': '连接器ID',
  'Connector inputs': '连接器输入',
  'Connector outputs': '连接器输出',
  'Process variables': '流程变量',
  'Variable events': '变量事件',
  'Variable name': '变量名称',
  'Variable assignment value': '变量赋值',
  'Listener ID': '监听器ID',
  'Listener type': '监听器类型',
  'Event type': '事件类型',

  // 属性面板 - 基本字段
  'Element': '元素',
  'Id': '标识',
  'ID': '标识',
  'Name': '名称',
  'Version': '版本',
  'version': '版本',
  'Version tag': '版本标签',
  'version tag': '版本标签',
  'versionTag': '版本标签',
  'Version tag binding': '版本标签绑定',
  'Executable': '可执行',
  'Process Type': '流程类型',
  'Process': '流程',
  'Process ID': '流程标识',
  'Process name': '流程名称',
  'Process documentation': '流程文档',
  'Participant Name': '参与者名称',
  'Type': '类型',
  'Value': '值',
  'Values': '值',
  'Key': '键',
  'Label': '标签',
  'Default value': '默认值',
  'Required': '必填',
  'Local': '本地',
  'Exclusive': '排他',

  // 属性面板 - 用户任务
  'User task': '用户任务',
  'Assignee': '处理人',
  'Candidate Users': '候选用户',
  'Candidate users': '候选用户',
  'Candidate Groups': '候选组',
  'Candidate groups': '候选组',
  'Candidate starter': '候选发起人',
  'Candidate starter users': '候选发起用户',
  'Candidate starter groups': '候选发起组',
  'Due Date': '到期时间',
  'Due date': '到期时间',
  'Follow up date': '跟踪日期',
  'Priority': '优先级',
  'Initiator': '发起人',
  'Start initiator': '发起人',
  'Delegate Expression': '委托表达式',
  'Delegate expression': '委托表达式',
  'Delegate Class': '委托类',
  'Delegate Variable Mapping': '委托变量映射',
  'Class': 'Java类',
  'Java class': 'Java类',
  'Expression': '表达式',
  'Async': '异步',
  'Asynchronous before': '异步前',
  'Asynchronous after': '异步后',

  // 属性面板 - 表单
  'Form Key': '表单Key',
  'Form key': '表单Key',
  'Form ID': '表单ID',
  'Form reference': '表单引用',
  'Form fields': '表单字段',
  'Form JSON configuration': '表单JSON配置',
  'Camunda Form': 'Camunda表单',
  'Camunda Form (embedded)': 'Camunda表单（内嵌）',
  'Camunda Form (linked)': 'Camunda表单（链接）',
  'Camunda Forms': 'Camunda表单',
  'Camunda user task': 'Camunda用户任务',
  'Custom form key': '自定义表单Key',
  'Custom type': '自定义类型',
  'Embedded or External Task Forms': '内嵌或外部任务表单',
  'External form reference': '外部表单引用',
  'External resource': '外部资源',
  'Generated Task Forms': '生成的任务表单',
  'Start event form documentation': '开始事件表单文档',
  'User task form documentation': '用户任务表单文档',
  'User task priority documentation': '用户任务优先级文档',
  'User task documentation': '用户任务文档',

  // 属性面板 - 多实例
  'Collection': '集合',
  'Element Variable': '元素变量',
  'Element variable': '元素变量',
  'Is Sequential': '是否顺序',
  'Loop cardinality': '循环基数',
  'Completion condition': '完成条件',
  'Multi instance': '多实例',
  'Active elements': '活动元素',
  'Active elements collection': '活动元素集合',
  'Input collection': '输入集合',
  'Input element': '输入元素',
  'Output collection': '输出集合',
  'Output element': '输出元素',

  // 属性面板 - 条件/网关
  'Condition': '条件',
  'Condition Expression': '条件表达式',
  'Condition expression': '条件表达式',
  'e.g. ${approved == true}': '例如 ${approved == true}',

  // 属性面板 - 脚本任务
  'Script Format': '脚本格式',
  'Script': '脚本',
  'Script type': '脚本类型',
  'Script task documentation': '脚本任务文档',
  'Inline script': '内联脚本',
  'Result Variable': '结果变量',
  'Result variable': '结果变量',
  'Format': '格式',
  'Resource': '资源',

  // 属性面板 - 消息/信号/错误/升级
  'Message': '消息',
  'Signal': '信号',
  'Error': '错误',
  'Escalation': '升级',
  'Timer': '定时器',
  'Message variable': '消息变量',
  'Global error reference': '全局错误引用',
  'Global escalation reference': '全局升级引用',
  'Global message reference': '全局消息引用',
  'Global signal reference': '全局信号引用',
  'Error event documentation': '错误事件文档',
  'Message boundary event documentation': '消息边界事件文档',
  'Message catch event documentation': '消息捕获事件文档',
  'Message start event documentation': '消息开始事件文档',
  'Message throw event documentation': '消息抛出事件文档',
  'Conditional event documentation': '条件事件文档',
  'Timer documentation': '定时器文档',
  'Documentation: Timer events': '文档：定时器事件',
  'Documentation: Variable events': '文档：变量事件',
  'Conditions documentation': '条件文档',
  'Subscription correlation key': '订阅关联键',
  'Subscription correlation key documentation': '订阅关联键文档',

  // 属性面板 - 调用活动
  'Called Element': '调用元素',
  'Called element': '调用元素',
  'Business Key': '业务Key',
  'Business key': '业务Key',
  'Business key expression': '业务Key表达式',
  'Variables': '变量',
  'Called decision': '调用决策',
  'Called decision documentation': '调用决策文档',
  'Decision ID': '决策ID',
  'Decision reference': '决策引用',
  'DMN decision': 'DMN决策',
  'Case ref': '用例引用',
  'Activity reference': '活动引用',
  'Wait for completion': '等待完成',
  'Cancel remaining instances': '取消剩余实例',
  'Called element version': '调用元素版本',
  'Called element binding': '调用元素绑定',
  'Called element tenant ID': '调用元素租户ID',
  'Deployment binding': '部署绑定',
  'Latest binding': '最新绑定',
  'Version tag by which the called process will be referenced.': '调用流程引用的版本标签。',
  'Version tag by which the called decision will be referenced.': '调用决策引用的版本标签。',
  'Version tag by which the linked form will be referenced.': '链接表单引用的版本标签。',
  'Version tag by which this process can be referenced.': '此流程可引用的版本标签。',
  'latest': '最新',
  'deployment': '部署',

  // 属性面板 - 服务任务/实现
  'Implementation': '实现方式',
  'Implementation type': '实现类型',
  'Service task documentation': '服务任务文档',
  'Send task documentation': '发送任务文档',
  'Receive task message documentation': '接收任务消息文档',
  'Business rule task documentation': '业务规则任务文档',
  'Call activity documentation': '调用活动文档',
  'Ad-hoc subprocess documentation': '自适应子流程文档',
  'Job type': '作业类型',
  'Job worker': '作业工作者',
  'External task': '外部任务',
  'Topic': '主题',
  'Retries': '重试次数',
  'Retry time cycle': '重试时间周期',
  'Task definition': '任务定义',
  'Task headers documentation': '任务头文档',
  'FEEL expression': 'FEEL表达式',
  'Code': '代码',
  'Code variable': '代码变量',
  'Throw expression': '抛出表达式',

  // 属性面板 - 映射
  'Map': '映射',
  'Map entries': '映射条目',
  'Map decision result': '映射决策结果',
  'List': '列表',
  'List values': '列表值',
  'Source': '来源',
  'Source expression': '来源表达式',
  'Target': '目标',
  'Propagate all variables': '传播所有变量',
  'Propagate all parent process variables': '传播所有父流程变量',
  'Propagate all child process variables': '传播所有子流程变量',
  'Output mappings documentation': '输出映射文档',
  'Input mappings documentation': '输入映射文档',

  // 属性面板 - 监听器
  'Event': '事件',
  'Readable': '可读',
  'Writable': '可写',
  'String': '字符串',
  'string': '字符串',
  'Long': '长整型',
  'long': '长整型',
  'Boolean': '布尔型',
  'boolean': '布尔型',
  'Date': '日期',
  'date': '日期',
  'Double': '双精度',
  'Integer': '整型',
  'Enum': '枚举',
  'enum': '枚举',
  'Text': '文本',
  'unnamed': '未命名',
  'empty': '空',
  'e.g. ${userList}': '例如 ${userList}',
  'e.g. user': '例如 user',
  'start': '开始',
  'Start': '开始',
  'end': '结束',
  'End': '结束',
  'take': '执行',
  'Take': '执行',
  'create': '创建',
  'Create': '创建',
  'assignment': '分配',
  'complete': '完成',
  'Complete': '完成',
  'delete': '删除',
  'update': '更新',
  'Update': '更新',
  'timeout': '超时',
  'Cancel': '取消',

  // 属性面板 - 定时器
  'Cycle': '周期',
  'Duration': '持续时间',
  'UTC time': 'UTC时间',
  '1 hour and 30 minutes': '1小时30分钟',
  '14 days': '14天',
  '15 seconds': '15秒',
  'every 10 seconds, up to 5 times': '每10秒，最多5次',
  'every day, infinitely': '每天，无限循环',
  'every hour on the hour from 9-5 p.m. UTC Monday-Friday': 'UTC时间周一至周五上午9点至下午5点每小时',
  'UTC plus 2 hours zone offset': 'UTC加2小时时区偏移',
  'How to configure a timer': '如何配置定时器',
  'A specific point in time defined as ISO 8601 combined date and time representation.': 'ISO 8601组合日期和时间表示的特定时间点。',
  'A time duration defined as ISO 8601 durations format.': 'ISO 8601持续时间格式定义的时间段。',
  'A cycle defined as ISO 8601 repeating intervals format, or a cron expression.': 'ISO 8601重复间隔格式或cron表达式定义的周期。',
  'A cycle defined as ISO 8601 repeating intervals format.': 'ISO 8601重复间隔格式定义的周期。',

  // 属性面板 - 提示文本
  'Select an element to edit its properties.': '选择一个元素以编辑其属性。',
  'Multiple elements are selected. Select a single element to edit its properties.': '已选择多个元素。请选择单个元素以编辑其属性。',
  'ID must be a valid QName.': '标识必须是有效的QName。',
  'ID must be unique.': '标识必须唯一。',
  'ID must not be empty.': '标识不能为空。',
  'ID must not contain prefix.': '标识不能包含前缀。',
  'ID must not contain spaces.': '标识不能包含空格。',
  'Create new ...': '创建新...',
  'Created in': '创建于',
  'Startable': '可启动',
  'Tasklist': '任务列表',
  'Tenant ID': '租户ID',
  'Time to live': '存活时间',
  'Binding': '绑定',
  'Before': '之前',
  'Before all': '全部之前',
  'Before each': '每次之前',
  'After': '之后',
  'After each': '每次之后',
  'On': '开',
  'Off': '关',
  'Compensation': '补偿',
  'Completion': '完成',
  'Refers to the process variable name': '引用流程变量名称',
  'This maps to the process definition key.': '映射到流程定义键。',
  'String or expression': '字符串或表达式',
  'Number of days before this resource is being cleaned up. If specified, takes precedence over the engine configuration.': '此资源被清理前的天数。如果指定，优先于引擎配置。',
  'The number of times the engine tries executing this activity if a worker signals a failure. The default is three.': '如果工作者报告失败，引擎尝试执行此活动的次数。默认为三次。',
  'The due date as an EL expression (e.g. ${someDate}) or an ISO date (e.g. 2015-06-26T09:54:00).': '到期时间为EL表达式（如 ${someDate}）或ISO日期（如 2015-06-26T09:54:00）。',
  'The follow up date as an EL expression (e.g. ${someDate}) or an ': '跟踪日期为EL表达式（如 ${someDate}）或',
  'Specify more than one group as a comma separated list.': '指定多个组，以逗号分隔。',
  'Specify more than one user as a comma separated list.': '指定多个用户，以逗号分隔。',
  'Specify more than one variable change event as a comma separated list. Variable change events are:': '指定多个变量变更事件，以逗号分隔。变量变更事件为：',
  'Specifies the priority of a user task. Must be an integer between 0 and 100. If no value is provided, the default value is 50. ': '指定用户任务的优先级。必须是0到100之间的整数。如果未提供值，默认值为50。',
  'Define the assignment, schedule, and priority of the user task. Assignee, candidate groups, and candidate users can be combined. Use due date and follow-up date to express deadlines and urgency. ': '定义用户任务的分配、计划和优先级。处理人、候选组和候选用户可以组合使用。使用到期日期和跟踪日期表示截止时间和紧急程度。',
  'Define the completion behavior of an ad-hoc subprocess. If no completion condition is set, it will be completed after all active elements have been completed. ': '定义自适应子流程的完成行为。如果未设置完成条件，将在所有活动元素完成后完成。',
  'Define a collection of elements which will be activated when the ad-hoc subprocess is reached. ': '定义到达自适应子流程时将激活的元素集合。',
  'Define how to collect the outputs of the ad-hoc subprocess. The output collection variable stores the list of results; the output element expression defines what each element contributes. ': '定义如何收集自适应子流程的输出。输出集合变量存储结果列表；输出元素表达式定义每个元素的贡献。',
  'Define an input collection expression that defines the collection to iterate over (e.g. ': '定义输入集合表达式，指定要迭代的集合（如 ',
  'Execute this task for each element of a given collection. ': '对给定集合中的每个元素执行此任务。',
  'Define a boolean condition expression that determines when this sequence flow is taken. ': '定义决定何时选择此顺序流的布尔条件表达式。',
  'Define the decision to evaluate and how to map back the evaluation result. ': '定义要评估的决策以及如何映射评估结果。',
  'Define the FEEL expression to evaluate and the variable to store the result in. ': '定义要评估的FEEL表达式以及存储结果的变量。',
  'Define the ID of the process to call (e.g. ': '定义要调用的流程ID（如 ',
  'Define the error to catch. Specify an error code (e.g. ': '定义要捕获的错误。指定错误代码（如 ',
  'Define the error to throw. Specify an error code (e.g. ': '定义要抛出的错误。指定错误代码（如 ',
  'Define the name of the variable that will contain the error code.': '定义包含错误代码的变量名称。',
  'Define the name of the variable that will contain the error message.': '定义包含错误消息的变量名称。',
  'Define the name of the variable that will contain the escalation code.': '定义包含升级代码的变量名称。',
  'Define static metadata passed to job workers alongside each job. Headers are not evaluated by the engine — use them for fixed worker configuration (e.g. ': '定义随每个作业传递给作业工作者的静态元数据。请求头不会被引擎评估——用于固定的工作者配置（如 ',
  'Add custom key-value metadata to this element. Extension properties have no effect on process execution — they can be used to attach configuration visible for other consumers of the BPMN diagram. ': '为此元素添加自定义键值元数据。扩展属性对流程执行没有影响——可用于附加对BPMN图其他消费者可见的配置。',
  'Add custom logic that reacts to various events in the workflow execution life-cycle. ': '添加对工作流执行生命周期中各种事件做出反应的自定义逻辑。',
  'Add input mappings to control what is passed to the activity as local variables. ': '添加输入映射以控制作为局部变量传递给活动的内容。',
  'Add output mappings to control which variables are merged back into the process scope. ': '添加输出映射以控制哪些变量合并回流程范围。',
  'Control which variables from the called process are merged back into the parent scope. By default, all child variables are propagated; use output mappings to selectively return specific variables. ': '控制被调用流程中的哪些变量合并回父范围。默认情况下，所有子变量都会传播；使用输出映射选择性地返回特定变量。',
  'If turned on, all variables from the child process instance will be propagated to the parent process instance.': '如果开启，子流程实例的所有变量将传播到父流程实例。',
  'If turned on, all variables from the parent process instance will be propagated to the child process instance.': '如果开启，父流程实例的所有变量将传播到子流程实例。',
  'Otherwise, only variables defined via input mappings will be propagated.': '否则，仅通过输入映射定义的变量将被传播。',
  'Otherwise, only variables defined via output mappings will be propagated.': '否则，仅通过输出映射定义的变量将被传播。',
  'To collect the output define the output collection and the output element expressions. ': '要收集输出，请定义输出集合和输出元素表达式。',
  'Configure the message that the task waits for. ': '配置任务等待的消息。',
  'Configure the message that this event waits for. ': '配置此事件等待的消息。',
  'Configure the message that will start this process instance. ': '配置将启动此流程实例的消息。',
  'Configure the message that will trigger this boundary event. ': '配置将触发此边界事件的消息。',
  'Specify the condition that triggers this event. ': '指定触发此事件的条件。',
  'Specify which job workers handle the event work. ': '指定哪些作业工作者处理事件工作。',
  'Specify which job workers handle the task work to evaluate business rules. ': '指定哪些作业工作者处理评估业务规则的任务工作。',
  'Specify which job workers handle the task work to execute a script. ': '指定哪些作业工作者处理执行脚本的任务工作。',
  'Specify which job workers handle the task work to execute a service (e.g. ': '指定哪些作业工作者处理执行服务的任务工作（如 ',
  'Specify which job workers handle the task work to send a message (e.g. ': '指定哪些作业工作者处理发送消息的任务工作（如 ',
  'React to user task lifecycle events by executing a job worker. ': '通过执行作业工作者来响应用户任务生命周期事件。',
  'Implement a user task managed by Camunda. To add a custom implementation, use a job worker. ': '实现由Camunda管理的用户任务。要添加自定义实现，请使用作业工作者。',
  'Implement a script task using an inline FEEL expression. To add a custom implementation, use a job worker. ': '使用内联FEEL表达式实现脚本任务。要添加自定义实现，请使用作业工作者。',
  'Implement the ad-hoc subprocess as a job worker instead of activating inner elements. The job type determines which worker handles the subprocess execution. ': '将自适应子流程实现为作业工作者而非激活内部元素。作业类型决定哪个工作者处理子流程执行。',
  'Evaluate a business rule, for example a DMN decision. To add a custom implementation, use a job worker. ': '评估业务规则，例如DMN决策。要添加自定义实现，请使用作业工作者。',
  'Link a form created with the Camunda Forms editor. Submitting this form will start a new process instance. ': '链接使用Camunda表单编辑器创建的表单。提交此表单将启动新的流程实例。',
  'Link a form created with the Camunda Forms editor. To associate a custom form, application, or URL to the user task, specify an external reference. ': '链接使用Camunda表单编辑器创建的表单。要将自定义表单、应用或URL关联到用户任务，请指定外部引用。',
  'Link or embed a form created with the Camunda Forms editor. To associate a custom form, application, or URL to the user task, specify a form key. ': '链接或嵌入使用Camunda表单编辑器创建的表单。要将自定义表单、应用或URL关联到用户任务，请指定表单Key。',
  'About conditional events.': '关于条件事件。',
  'Learn how to define conditions.': '了解如何定义条件。',
  'Learn more.': '了解更多。',
  'Variable events that trigger the condition evaluation. If none selected, all variable events will trigger the condition evaluation. ': '触发条件评估的变量事件。如果未选择，所有变量事件将触发条件评估。',
  'Identifier computed from the process context that is used to correlate an incoming message (e.g. ': '从流程上下文计算的标识符，用于关联传入消息（如 ',
  'A FEEL expression that determines whether the event should trigger. ': '决定事件是否应触发的FEEL表达式。',
  'Uses the most recent deployed resource.': '使用最新部署的资源。',
  'Uses the most recent deployed resource with the given version tag.': '使用具有给定版本标签的最新部署资源。',
  'Uses the resource found in the same deployment.': '使用在同一部署中找到的资源。',
  'Element documentation': '元素文档',

  // 属性面板 - 映射结果类型
  'collectEntries (List<Object>)': 'collectEntries (List<Object>)',
  'resultList (List<Map<String, Object>>)': 'resultList (List<Map<String, Object>>)',
  'singleResult (Map<String, Object>)': 'singleResult (Map<String, Object>)',
  'singleEntry (TypedValue)': 'singleEntry (TypedValue)',

  // 属性面板 - 特殊占位符
  '<custom type>': '<自定义类型>',
  '<empty>': '<空>',
  '<none>': '<无>',
  'Start typing "': '开始输入"',
  ' or ': ' 或 ',
  'Ad-hoc completion': '自适应完成',
  'Ad-hoc implementation': '自适应实现',
  'Ad-hoc output collection': '自适应输出集合',
  'Ad-hoc output element': '自适应输出元素',
  'Ad-hoc subProcess implementation': '自适应子流程实现',

  // 通用提示
  'no diagram to display': '没有要显示的流程图',
  'Undo': '撤销',
  'Redo': '重做',
  'Zoom in': '放大',
  'Zoom out': '缩小',
  'Reset zoom': '重置缩放',
  'Fit viewport': '适应画布',
  'Move to origin': '移到原点',
  'Export': '导出',
  'Save': '保存',
  'Open': '打开',
  'New': '新建'
}

export default function customTranslate(template: string, replacements: Record<string, string> = {}) {
  let translatedText = translations[template] || template
  return translatedText.replace(/{([^}]+)}/g, (_: string, key: string) => {
    return replacements[key] || `{${key}}`
  })
}
